services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
  opa:
    image: openpolicyagent/opa
    ports:
    - "8181:8181"
    volumes:
    - ./models/opa:/rego
    command: run --server --addr :8181 /rego/demo-rules.rego