server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # "auth" is the name of the Keycloak container in Docker Compose
          issuer-uri: http://auth:8080/realms/demo

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

open-policy-agent:
  # "opa" is the name of the Open Policy Agent container in Docker Compose
  uri: http://opa:8181/v1/data/demo/allow